name: siwa
description: A travel app for Siwa Oasis.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  fl_chart: ^1.1.1
  table_calendar: ^3.0.9
  carousel_slider: ^5.1.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  sign_in_with_apple: ^7.0.1
  flutter_lucide: ^1.7.0
  go_router: ^16.2.4
  share_plus: ^12.0.0
  qr_flutter: ^4.1.0
  flutter_animate: ^4.5.2
  confetti: ^0.8.0
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  styled_widget: ^0.4.1
  cached_network_image: ^3.3.0
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.3
  dotted_border: ^3.1.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/translations/